export const sentences = [
    'Hello there, My name is Samuel Oluwatimileyin, a senior frontend developer who is familiar with varieties of frontend technologies and has experience working as a backend developer and full stack developer; i have worked with great company bot locally and internationally. Having worked with great companies both locally and internationally, i look forward to a great opportunity where i can use my skills to contribute to a company i love and your company is a perfect fit.',

    'Mymoneykarma give access to their learning center; Whether you want to break down complex finance concepts, compare different strategies, understand banking processes, or evaluate the market, they have the right resource for you!. Visit their website at mymoneykarma.com/learning-center for more information.',

    'This is a simple app for users to test and improve their typing skills. The app will present the user with a random text paragraph or the user can c/p his own choice of the paragraph. We will call it a challenge. Then the user will select the time duration of the test it can be 1 m, 2m 5m, or custom. Once the test is set up he can start the test and hence the timer. The user needs to type the paragraph in another text box as it is. For each correct word, he will get 1 point for each incorrect word he types he will receive 0 points. Total points will be the total no of words in the paragraph.At the end of the test, the user will be presented with his score which is his typing accuracy and speed.',

    'One of the mission of mymoneykarma is customer first. They exist because of our customers and obsess to provide them with the best experience. They consider the impact on customers lives before they think about our own interests. Another mission is trust; they work tirelessly to earn and keep customer trust by helping them save money or make money. Another is excellence; they demand excellence and have relentlessly high standards for theirselves and the products and services they deliver.',

    'At mymoneykarma, one of India’s fastest growing FinTech companies, they are redefining the personal finance landscape and putting you at the center of it. They make you understand your current financial position and how you can improve it. They also give personalized recommendations to improve your finances. Their recommendations will always be unbiased and focused on improving your finances.'
]